# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_ecommerce'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_ecommerce'

# These configurations specify where dbt should look for different types of files.
model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

clean-targets:
  - 'target'
  - 'dbt_packages'

# Configuring models
models:
  dbt_ecommerce:
    staging:
      +materialized: incremental
      +schema: staging
      +incremental_strategy: append

    marts:
      core:
        +materialized: incremental
        +schema: core
        +incremental_strategy: append

      metrics:
        +materialized: table
        +schema: metrics
